// 예외조항처리

// try {
//   // 실행시킬 코드
//   console.log("시작");
//   add(); // 의도적인 에러
//   console.log("실행 중...");
//   console.log("끝");
// } catch (err) {
//   // try문을 실행시켰을 때, 어떤 에러사함이 발생될 경우, 실행시킬 명령문
//   console.log(`오류발생 : ${err.name}`);
//   console.log(`오류발생 : ${err.message}`);
//   //ReferenceError(name): add is not defined(message)

// }
// console.log("종료");
// // 에러가 발생되면 에러객체가 나옴 이벤트 e객체처럼 err
